version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:7.0
    container_name: feishu-notes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hxg20021126
      MONGO_INITDB_DATABASE: feishu-notes
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - feishu-notes-network

  # Redis 缓存
  redis:
    image: redis:7.2-alpine
    container_name: feishu-notes-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass hxg20021126
    volumes:
      - redis_data:/data
    networks:
      - feishu-notes-network

  # 后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: feishu-notes-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:hxg20021126@mongodb:27017/feishu-notes?authSource=admin
      REDIS_URL: redis://:hxg20021126@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    networks:
      - feishu-notes-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: feishu-notes-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - feishu-notes-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  feishu-notes-network:
    driver: bridge